name: 'Junit Coverage Report (with monorepo support)'
description: 'Comment a pull request with unit tests and coverage reports (with monorepo support)'
author: 'Anh Pham'
branding:
  icon: 'square'
  color: 'purple'

inputs:
  github-token:
    description: GitHub Access Token
    default: ${{ github.token }}
    required: true

  junit-path:
    description: 'JUnit file path'
    default: './unit.xml'
    required: false

  coverage-path:
    description: 'Coverage file path'
    default: './coverage.xml'
    required: false

  project-name:
    description: 'Project name to show in comment'
    default: ${{ github.repository }}
    required: false
  
  project-dir:
    description: 'Project directory in monorepo'
    default: ''
    required: false
  
  project-coverage-dir:
    description: 'Project coverage directory in monorepo (relative to project-dir)'
    required: false

  template-path:
    description: 'Custom template file path'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
